### ISSUE TITLE
Repeated adding of mod

### ISSUE THREAD

**Issue by orandaadnaro** [revblaze/BaldursModManager#32]
v0.1.2

Ive added ring of gods & animated framework twice - this has resulted in an empty selection by the mod names on the left hand panel. Therefor i cant enabler/disable the apps.

I'm running this on a m3 iMac. 

Also no added mods seem to be active ie additional outfits armor etc. So I doubt if the mod manager is working. 

BTW I've never played D&D and only 5hrs of BG so my knowledge of the actual game controls and menus is limited.

**Comment by revblaze** [comment]
Would you mind linking me the Nexus mod pages, and the specific versions downloaded for each (in case they get updated before I have a chance to look into this)? Thanks for reporting this!

**Comment by orandaadnaro** [comment]
Hi Justin



https://www.nexusmods.com/baldursgate3/mods/6308￼
Ring of Gods - Overpowered cheat item
nexusmods.com

Version 1.0.0


https://www.nexusmods.com/baldursgate3/mods/6045￼
Version 1.2.1.0

Best wishes


Pete Bradbury

**Comment by revblaze** [comment]
Awesome! I'll see if I can find some time to look into this and figure out what's going on.

**Comment by orandaadnaro** [comment]
Hi Justin

I hope you might be able to answer this question

If I need to install the Script Extender Launcher <https://github.com/Norbyte/bg3se/releases/tag/updater-20240329> (on a m3 Mac running the Mac version of Baldurs Gate (which is my setup)  this is a file called DWrite.dll needing to be installed at 

C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\bin   will this work on not under my setup?  There’s no bin folder on the BG on Mac


There a mention :


Linux (Proton) additional instructions (DO NOT DO THIS IF YOU ARE ON WINDOWS!)

Right-click the game in the games library in Steam
Click Properties...
Click SET LAUNCH OPTIONS... button
Enter WINEDLLOVERRIDES="DWrite.dll=n,b" PROTON_NO_ESYNC=1 %command%

But again no mention of Mac suggests use of wine


BTW Ive also got parallels running BG with vortex, but it lags very badly compared to the
Native Mac BG


If you’ve any BG m1/2/3 Mac user group you can point me to - feel free to 

:-)

**Comment by orandaadnaro** [comment]
Hi Justin

I thought you ought to know:

Just by dragging and rendering the mods mentioned, the became available to make enabled/disable - so that’s good news !

However I’m still not seeing any of these appearing in the game, is there a way of seeing active mods listed in the game itself?
