### ISSUE TITLE
Had to chmod +x Contents/MacOS/BaldursModManager

### ISSUE THREAD

**Issue by mtklein** [revblaze/BaldursModManager#41]
I just downloaded the latest release (thank you!) and had to chmod +x the main executable inside the released .app.
That might be confusing?  The error you get it kind of obtuse: 

`
$ open Applications/BaldursModManager.app/
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000002bc5d0 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}`

**Comment by buzsh** [comment]
This is bizarre. Thank you for reporting this! I'm looking into it.

**Comment by buzsh** [comment]
@mtklein would you be able to confirm for me if you can open this hotfixed version from the CLI:

[BaldursModManager-hotfix-201.app.zip](https://github.com/revblaze/BaldursModManager/files/15461717/BaldursModManager-hotfix-201.app.zip)

**Comment by mtklein** [comment]
Yes, all good with the hotfix for me.

**Comment by buzsh** [comment]
Excellent! Thank you for being the test subject. Lady of sorrows guide you.

**Comment by buzsh** [comment]
Resolved: https://github.com/revblaze/BaldursModManager/commit/277e99cc32c9a03696471c6ff1aeb7836c101a3f
